Milestone for complete project adding Bootstrap
harshdeepkanhai/newsweek-clone pull request #1
Opened 2020-08-25 17:37 UTC by harshdeepkanhai

Used Bootstrap to build the Newsweek clone

2020-09-02 21:17 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */ 
![image](https://user-images.githubusercontent.com/56762529/92037364-07a67880-ed48-11ea-839b-e821067d6858.png)


- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/92037227-d9289d80-ed47-11ea-9c6f-cce7f9cefca3.png)


#### General issues:
- [x] In Large, medium and small screens, your page is missing the EDITOR'S PICK and those other sections such as U.S., World, Business and so on (check that gif made at medium screens)
##### Yours
![ezgif com-optimize](https://user-images.githubusercontent.com/56762529/92036913-556eb100-ed47-11ea-8993-22c9321ae76c.gif)


##### Original one:
![ezgif com-optimize(1)](https://user-images.githubusercontent.com/56762529/92037033-8818a980-ed47-11ea-8729-524009f80eb9.gif)

#### Large screen issues:
- [x] At the bottom of the page, the **newsletter image is too shrinked** take care of that! ⤵ 😎
##### Yours
![image](https://user-images.githubusercontent.com/56762529/92036497-b47ff600-ed46-11ea-9f2f-a22fc8723c78.png)
##### Original
![image](https://user-images.githubusercontent.com/56762529/92032615-d7a7a700-ed40-11ea-8cc1-f411f10b2514.png)

#### Medium screens
- [x] Please Fix that overlapping ⤵
![image](https://user-images.githubusercontent.com/56762529/92033998-ff980a00-ed42-11ea-8232-ada2d567e66b.png)
- [x] At the bottom of the page, the **newsletter image is too shrinked** take care of that! ⤵ 😎
![image](https://user-images.githubusercontent.com/56762529/92034080-176f8e00-ed43-11ea-9928-d3facb0c0b58.png)
- [x] At the "The debate" and "Opinion" section, those avatar images are too big, fix that.
##### Yours
![image](https://user-images.githubusercontent.com/56762529/92034619-e3e13380-ed43-11ea-82ab-7a0d83f92120.png)
##### Original one
![image](https://user-images.githubusercontent.com/56762529/92034650-ecd20500-ed43-11ea-9492-d5e39f4cf1ce.png)

#### Small screen issues:
- [x] The first section should be Top Story, not Featured Stories ⤵
##### Your's:
![image](https://user-images.githubusercontent.com/56762529/92033591-49ccbb80-ed42-11ea-87ec-c1f37ddaf55f.png)
##### Original one:
![image](https://user-images.githubusercontent.com/56762529/92033616-54875080-ed42-11ea-9c1f-35207f124ffb.png)

- [x] In small screens your your footer don't look like the original one, because the items are too spaced, kindly improve it
##### Yours:
![image](https://user-images.githubusercontent.com/56762529/92032950-4553d300-ed41-11ea-8b19-d687b742344e.png)
##### Original one:
![image](https://user-images.githubusercontent.com/56762529/92033002-53a1ef00-ed41-11ea-93e5-898c03c500e2.png)
- [x] Your page is facing **overflow at the horizontal axis**,and the **newsletter image is too shrinked** take care of that! ⤵ 😎

 [![Image from Gyazo](https://i.gyazo.com/5b569feeaac31ae8ce80112fcb6f1c7a.gif)](https://gyazo.com/5b569feeaac31ae8ce80112fcb6f1c7a)
`Kev tip: For fix overflow issues, use this rule: * { border: 1px solid red }, so you'll be able to see the limits of all your elements and spot those who are overflowing!`


## [OPTIONAL CHANGES]
- [ ] Improve the layout (e.g.: sizings, spacing, font, icons) to make it more similar to the original page;
- [ ] Add a favicon to make it more similar to the original page;

## Please make the required changes and resubmit for a new code review once you are ready💪

<img src="https://media1.giphy.com/media/UjCXeFnYcI2R2/giphy.gif?cid=ecf05e47f85sszmncvz9gstxysd956tlk5y2gojz9vumla10&amp;rid=giphy.gif">

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-02 21:17 UTC, kevincappuccino commented on assets/stylesheets/main.css
> +} */
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-02 21:19 UTC, kevincappuccino commented on assets/stylesheets/main.css
> +  } */
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-03 18:00 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello @harshdeepkanhai :wave: 

### Thank you for making almost all of the changes requested by the previous TSE, but we still have some details to change. Please read my suggestions below.

## All screens

- [ ] You still have a horizontal scroll, please fix it. Think about what could be causing it, maybe it's a container that's causing that?

- [ ] You fixed only one of these images in the 'The Debate' section, kindly fix the others:

![Screenshot from 2020-09-03 14-57-48](https://user-images.githubusercontent.com/59691171/92150561-f4ea7d00-edf5-11ea-80a1-abccf4624581.png)
<br>

## General

- [ ] Please fix your screenshot in your README file, it's not showing.

- [ ] Please fix your Live Link, it's not currently working.

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-04 15:30 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far :clap: :clap: :+1: but you need to work more on your project to make it looks perfect :100:.

- [x] on mobile view the editor's pick section is not taking the full width of the page, make it like that.

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92255365-203e9c00-eeca-11ea-9654-96bb5bb43e10.png) | ![image](https://user-images.githubusercontent.com/34653764/92255407-2df42180-eeca-11ea-9ebe-3f630f51d7eb.png) |

- [ ] on mobile view also, you need to give more with to the newsletter form and also give it some border:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92255698-9a6f2080-eeca-11ea-90f3-ad35b0a7f705.png) | ![image](https://user-images.githubusercontent.com/34653764/92255625-81ff0600-eeca-11ea-82f4-6669ed053479.png) |

- [ ] on the tablet view, the debate section should take the full width of the page:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92256533-c0e18b80-eecb-11ea-9e60-967677cd979b.png) | ![image](https://user-images.githubusercontent.com/34653764/92255923-e326d980-eeca-11ea-87db-28cad0f74c68.png) |

- [ ] on the tablet view also, the editor's pick section should take only two articles in a row, not four.

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92256015-06518900-eecb-11ea-80d9-c62a636f5f0c.png) | ![image](https://user-images.githubusercontent.com/34653764/92256072-21bc9400-eecb-11ea-814e-153c8bfb40c8.png) |

- [ ] also on the tablet view, you need to fix the newsletter and subscribe sections.

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92256625-d9ea3c80-eecb-11ea-9531-d92560ea2fa5.png) | ![image](https://user-images.githubusercontent.com/34653764/92256201-53cdf600-eecb-11ea-8573-5e50ff64248d.png) |

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-09-04 17:25 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello again @harshdeepkanhai :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: **Just please don't forget to update the Live Link in your README file** :+1: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-04 18:02 UTC, merged